services:
  geoserver:
    image: kartoza/geoserver:latest
    ports:
      - "8080:8080"
    environment:
      - GEOSERVER_ADMIN_USER=admin
      - GEOSERVER_ADMIN_PASSWORD=geoserver
      - GEOSERVER_DATA_DIR=/var/lib/geoserver_data
      - SAMPLE_DATA=true
