/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { PreviewError } from "./lib/errors";
import { MapGeoJSONFeature } from "maplibre-gl";
export { PreviewError } from "./lib/errors";
export { MapGeoJSONFeature } from "maplibre-gl";
export namespace Components {
    interface OgmAlerts {
        "error"?: PreviewError;
        "theme": 'light' | 'dark';
    }
    interface OgmAttributes {
        /**
          * @default []
         */
        "features": MapGeoJSONFeature[];
    }
    interface OgmImage {
        /**
          * @default 0
         */
        "padding": number;
        "source": IIIFSource;
        "theme": 'light' | 'dark';
    }
    interface OgmMap {
        "easeMapTo": (options: maplibregl.EaseToOptions) => Promise<maplibregl.Map>;
        /**
          * @default 0
         */
        "padding": number;
        "source": Source;
        "theme": 'light' | 'dark';
    }
    interface OgmMenubar {
        /**
          * @default false
         */
        "loading": boolean;
        "record": OgmRecord;
        "theme": 'light' | 'dark';
    }
    interface OgmMetadata {
        "fieldNames": string[];
        "record": OgmRecord;
        "theme": 'light' | 'dark';
    }
    interface OgmPreview {
        "previewOpacity": number;
        "sidebarPadding": number;
        "source": Source;
        "theme": 'light' | 'dark';
    }
    interface OgmPreviews {
        "previewOpacity": number;
        "record": OgmRecord;
        "sidebarPadding": number;
        "theme": 'light' | 'dark';
    }
    interface OgmSettings {
        "record": OgmRecord;
    }
    interface OgmSidebar {
        /**
          * @default false
         */
        "open": boolean;
        "record": OgmRecord;
        "theme": 'light' | 'dark';
    }
    interface OgmViewer {
        "loadRecord": (record: OgmRecord) => Promise<void>;
        "recordUrl": string;
        /**
          * @default this.getThemePreference()
         */
        "theme": 'light' | 'dark';
    }
}
export interface OgmAttributesCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLOgmAttributesElement;
}
export interface OgmImageCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLOgmImageElement;
}
export interface OgmMapCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLOgmMapElement;
}
export interface OgmMenubarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLOgmMenubarElement;
}
export interface OgmSettingsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLOgmSettingsElement;
}
declare global {
    interface HTMLOgmAlertsElement extends Components.OgmAlerts, HTMLStencilElement {
    }
    var HTMLOgmAlertsElement: {
        prototype: HTMLOgmAlertsElement;
        new (): HTMLOgmAlertsElement;
    };
    interface HTMLOgmAttributesElementEventMap {
        "featureSelected": MapGeoJSONFeature;
    }
    interface HTMLOgmAttributesElement extends Components.OgmAttributes, HTMLStencilElement {
        addEventListener<K extends keyof HTMLOgmAttributesElementEventMap>(type: K, listener: (this: HTMLOgmAttributesElement, ev: OgmAttributesCustomEvent<HTMLOgmAttributesElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLOgmAttributesElementEventMap>(type: K, listener: (this: HTMLOgmAttributesElement, ev: OgmAttributesCustomEvent<HTMLOgmAttributesElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLOgmAttributesElement: {
        prototype: HTMLOgmAttributesElement;
        new (): HTMLOgmAttributesElement;
    };
    interface HTMLOgmImageElementEventMap {
        "imageLoaded": void;
        "imageLoading": void;
        "previewError": PreviewError;
    }
    interface HTMLOgmImageElement extends Components.OgmImage, HTMLStencilElement {
        addEventListener<K extends keyof HTMLOgmImageElementEventMap>(type: K, listener: (this: HTMLOgmImageElement, ev: OgmImageCustomEvent<HTMLOgmImageElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLOgmImageElementEventMap>(type: K, listener: (this: HTMLOgmImageElement, ev: OgmImageCustomEvent<HTMLOgmImageElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLOgmImageElement: {
        prototype: HTMLOgmImageElement;
        new (): HTMLOgmImageElement;
    };
    interface HTMLOgmMapElementEventMap {
        "mapIdle": void;
        "mapLoading": void;
        "previewError": PreviewError;
    }
    interface HTMLOgmMapElement extends Components.OgmMap, HTMLStencilElement {
        addEventListener<K extends keyof HTMLOgmMapElementEventMap>(type: K, listener: (this: HTMLOgmMapElement, ev: OgmMapCustomEvent<HTMLOgmMapElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLOgmMapElementEventMap>(type: K, listener: (this: HTMLOgmMapElement, ev: OgmMapCustomEvent<HTMLOgmMapElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLOgmMapElement: {
        prototype: HTMLOgmMapElement;
        new (): HTMLOgmMapElement;
    };
    interface HTMLOgmMenubarElementEventMap {
        "sidebarToggled": any;
    }
    interface HTMLOgmMenubarElement extends Components.OgmMenubar, HTMLStencilElement {
        addEventListener<K extends keyof HTMLOgmMenubarElementEventMap>(type: K, listener: (this: HTMLOgmMenubarElement, ev: OgmMenubarCustomEvent<HTMLOgmMenubarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLOgmMenubarElementEventMap>(type: K, listener: (this: HTMLOgmMenubarElement, ev: OgmMenubarCustomEvent<HTMLOgmMenubarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLOgmMenubarElement: {
        prototype: HTMLOgmMenubarElement;
        new (): HTMLOgmMenubarElement;
    };
    interface HTMLOgmMetadataElement extends Components.OgmMetadata, HTMLStencilElement {
    }
    var HTMLOgmMetadataElement: {
        prototype: HTMLOgmMetadataElement;
        new (): HTMLOgmMetadataElement;
    };
    interface HTMLOgmPreviewElement extends Components.OgmPreview, HTMLStencilElement {
    }
    var HTMLOgmPreviewElement: {
        prototype: HTMLOgmPreviewElement;
        new (): HTMLOgmPreviewElement;
    };
    interface HTMLOgmPreviewsElement extends Components.OgmPreviews, HTMLStencilElement {
    }
    var HTMLOgmPreviewsElement: {
        prototype: HTMLOgmPreviewsElement;
        new (): HTMLOgmPreviewsElement;
    };
    interface HTMLOgmSettingsElementEventMap {
        "opacityChange": number;
    }
    interface HTMLOgmSettingsElement extends Components.OgmSettings, HTMLStencilElement {
        addEventListener<K extends keyof HTMLOgmSettingsElementEventMap>(type: K, listener: (this: HTMLOgmSettingsElement, ev: OgmSettingsCustomEvent<HTMLOgmSettingsElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLOgmSettingsElementEventMap>(type: K, listener: (this: HTMLOgmSettingsElement, ev: OgmSettingsCustomEvent<HTMLOgmSettingsElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLOgmSettingsElement: {
        prototype: HTMLOgmSettingsElement;
        new (): HTMLOgmSettingsElement;
    };
    interface HTMLOgmSidebarElement extends Components.OgmSidebar, HTMLStencilElement {
    }
    var HTMLOgmSidebarElement: {
        prototype: HTMLOgmSidebarElement;
        new (): HTMLOgmSidebarElement;
    };
    interface HTMLOgmViewerElement extends Components.OgmViewer, HTMLStencilElement {
    }
    var HTMLOgmViewerElement: {
        prototype: HTMLOgmViewerElement;
        new (): HTMLOgmViewerElement;
    };
    interface HTMLElementTagNameMap {
        "ogm-alerts": HTMLOgmAlertsElement;
        "ogm-attributes": HTMLOgmAttributesElement;
        "ogm-image": HTMLOgmImageElement;
        "ogm-map": HTMLOgmMapElement;
        "ogm-menubar": HTMLOgmMenubarElement;
        "ogm-metadata": HTMLOgmMetadataElement;
        "ogm-preview": HTMLOgmPreviewElement;
        "ogm-previews": HTMLOgmPreviewsElement;
        "ogm-settings": HTMLOgmSettingsElement;
        "ogm-sidebar": HTMLOgmSidebarElement;
        "ogm-viewer": HTMLOgmViewerElement;
    }
}
declare namespace LocalJSX {
    interface OgmAlerts {
        "error"?: PreviewError;
        "theme"?: 'light' | 'dark';
    }
    interface OgmAttributes {
        /**
          * @default []
         */
        "features"?: MapGeoJSONFeature[];
        "onFeatureSelected"?: (event: OgmAttributesCustomEvent<MapGeoJSONFeature>) => void;
    }
    interface OgmImage {
        "onImageLoaded"?: (event: OgmImageCustomEvent<void>) => void;
        "onImageLoading"?: (event: OgmImageCustomEvent<void>) => void;
        "onPreviewError"?: (event: OgmImageCustomEvent<PreviewError>) => void;
        /**
          * @default 0
         */
        "padding"?: number;
        "source"?: IIIFSource;
        "theme"?: 'light' | 'dark';
    }
    interface OgmMap {
        "onMapIdle"?: (event: OgmMapCustomEvent<void>) => void;
        "onMapLoading"?: (event: OgmMapCustomEvent<void>) => void;
        "onPreviewError"?: (event: OgmMapCustomEvent<PreviewError>) => void;
        /**
          * @default 0
         */
        "padding"?: number;
        "source"?: Source;
        "theme"?: 'light' | 'dark';
    }
    interface OgmMenubar {
        /**
          * @default false
         */
        "loading"?: boolean;
        "onSidebarToggled"?: (event: OgmMenubarCustomEvent<any>) => void;
        "record"?: OgmRecord;
        "theme"?: 'light' | 'dark';
    }
    interface OgmMetadata {
        "fieldNames"?: string[];
        "record"?: OgmRecord;
        "theme"?: 'light' | 'dark';
    }
    interface OgmPreview {
        "previewOpacity"?: number;
        "sidebarPadding"?: number;
        "source"?: Source;
        "theme"?: 'light' | 'dark';
    }
    interface OgmPreviews {
        "previewOpacity"?: number;
        "record"?: OgmRecord;
        "sidebarPadding"?: number;
        "theme"?: 'light' | 'dark';
    }
    interface OgmSettings {
        "onOpacityChange"?: (event: OgmSettingsCustomEvent<number>) => void;
        "record"?: OgmRecord;
    }
    interface OgmSidebar {
        /**
          * @default false
         */
        "open"?: boolean;
        "record"?: OgmRecord;
        "theme"?: 'light' | 'dark';
    }
    interface OgmViewer {
        "recordUrl"?: string;
        /**
          * @default this.getThemePreference()
         */
        "theme"?: 'light' | 'dark';
    }

    interface OgmAlertsAttributes {
        "theme": 'light' | 'dark';
    }
    interface OgmImageAttributes {
        "theme": 'light' | 'dark';
        "padding": number;
    }
    interface OgmMapAttributes {
        "theme": 'light' | 'dark';
        "padding": number;
    }
    interface OgmMenubarAttributes {
        "theme": 'light' | 'dark';
        "loading": boolean;
    }
    interface OgmMetadataAttributes {
        "theme": 'light' | 'dark';
    }
    interface OgmPreviewAttributes {
        "theme": 'light' | 'dark';
        "previewOpacity": number;
        "sidebarPadding": number;
    }
    interface OgmPreviewsAttributes {
        "theme": 'light' | 'dark';
        "previewOpacity": number;
        "sidebarPadding": number;
    }
    interface OgmSidebarAttributes {
        "theme": 'light' | 'dark';
        "open": boolean;
    }
    interface OgmViewerAttributes {
        "recordUrl": string;
        "theme": 'light' | 'dark';
    }

    interface IntrinsicElements {
        "ogm-alerts": Omit<OgmAlerts, keyof OgmAlertsAttributes> & { [K in keyof OgmAlerts & keyof OgmAlertsAttributes]?: OgmAlerts[K] } & { [K in keyof OgmAlerts & keyof OgmAlertsAttributes as `attr:${K}`]?: OgmAlertsAttributes[K] } & { [K in keyof OgmAlerts & keyof OgmAlertsAttributes as `prop:${K}`]?: OgmAlerts[K] };
        "ogm-attributes": OgmAttributes;
        "ogm-image": Omit<OgmImage, keyof OgmImageAttributes> & { [K in keyof OgmImage & keyof OgmImageAttributes]?: OgmImage[K] } & { [K in keyof OgmImage & keyof OgmImageAttributes as `attr:${K}`]?: OgmImageAttributes[K] } & { [K in keyof OgmImage & keyof OgmImageAttributes as `prop:${K}`]?: OgmImage[K] };
        "ogm-map": Omit<OgmMap, keyof OgmMapAttributes> & { [K in keyof OgmMap & keyof OgmMapAttributes]?: OgmMap[K] } & { [K in keyof OgmMap & keyof OgmMapAttributes as `attr:${K}`]?: OgmMapAttributes[K] } & { [K in keyof OgmMap & keyof OgmMapAttributes as `prop:${K}`]?: OgmMap[K] };
        "ogm-menubar": Omit<OgmMenubar, keyof OgmMenubarAttributes> & { [K in keyof OgmMenubar & keyof OgmMenubarAttributes]?: OgmMenubar[K] } & { [K in keyof OgmMenubar & keyof OgmMenubarAttributes as `attr:${K}`]?: OgmMenubarAttributes[K] } & { [K in keyof OgmMenubar & keyof OgmMenubarAttributes as `prop:${K}`]?: OgmMenubar[K] };
        "ogm-metadata": Omit<OgmMetadata, keyof OgmMetadataAttributes> & { [K in keyof OgmMetadata & keyof OgmMetadataAttributes]?: OgmMetadata[K] } & { [K in keyof OgmMetadata & keyof OgmMetadataAttributes as `attr:${K}`]?: OgmMetadataAttributes[K] } & { [K in keyof OgmMetadata & keyof OgmMetadataAttributes as `prop:${K}`]?: OgmMetadata[K] };
        "ogm-preview": Omit<OgmPreview, keyof OgmPreviewAttributes> & { [K in keyof OgmPreview & keyof OgmPreviewAttributes]?: OgmPreview[K] } & { [K in keyof OgmPreview & keyof OgmPreviewAttributes as `attr:${K}`]?: OgmPreviewAttributes[K] } & { [K in keyof OgmPreview & keyof OgmPreviewAttributes as `prop:${K}`]?: OgmPreview[K] };
        "ogm-previews": Omit<OgmPreviews, keyof OgmPreviewsAttributes> & { [K in keyof OgmPreviews & keyof OgmPreviewsAttributes]?: OgmPreviews[K] } & { [K in keyof OgmPreviews & keyof OgmPreviewsAttributes as `attr:${K}`]?: OgmPreviewsAttributes[K] } & { [K in keyof OgmPreviews & keyof OgmPreviewsAttributes as `prop:${K}`]?: OgmPreviews[K] };
        "ogm-settings": OgmSettings;
        "ogm-sidebar": Omit<OgmSidebar, keyof OgmSidebarAttributes> & { [K in keyof OgmSidebar & keyof OgmSidebarAttributes]?: OgmSidebar[K] } & { [K in keyof OgmSidebar & keyof OgmSidebarAttributes as `attr:${K}`]?: OgmSidebarAttributes[K] } & { [K in keyof OgmSidebar & keyof OgmSidebarAttributes as `prop:${K}`]?: OgmSidebar[K] };
        "ogm-viewer": Omit<OgmViewer, keyof OgmViewerAttributes> & { [K in keyof OgmViewer & keyof OgmViewerAttributes]?: OgmViewer[K] } & { [K in keyof OgmViewer & keyof OgmViewerAttributes as `attr:${K}`]?: OgmViewerAttributes[K] } & { [K in keyof OgmViewer & keyof OgmViewerAttributes as `prop:${K}`]?: OgmViewer[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ogm-alerts": LocalJSX.IntrinsicElements["ogm-alerts"] & JSXBase.HTMLAttributes<HTMLOgmAlertsElement>;
            "ogm-attributes": LocalJSX.IntrinsicElements["ogm-attributes"] & JSXBase.HTMLAttributes<HTMLOgmAttributesElement>;
            "ogm-image": LocalJSX.IntrinsicElements["ogm-image"] & JSXBase.HTMLAttributes<HTMLOgmImageElement>;
            "ogm-map": LocalJSX.IntrinsicElements["ogm-map"] & JSXBase.HTMLAttributes<HTMLOgmMapElement>;
            "ogm-menubar": LocalJSX.IntrinsicElements["ogm-menubar"] & JSXBase.HTMLAttributes<HTMLOgmMenubarElement>;
            "ogm-metadata": LocalJSX.IntrinsicElements["ogm-metadata"] & JSXBase.HTMLAttributes<HTMLOgmMetadataElement>;
            "ogm-preview": LocalJSX.IntrinsicElements["ogm-preview"] & JSXBase.HTMLAttributes<HTMLOgmPreviewElement>;
            "ogm-previews": LocalJSX.IntrinsicElements["ogm-previews"] & JSXBase.HTMLAttributes<HTMLOgmPreviewsElement>;
            "ogm-settings": LocalJSX.IntrinsicElements["ogm-settings"] & JSXBase.HTMLAttributes<HTMLOgmSettingsElement>;
            "ogm-sidebar": LocalJSX.IntrinsicElements["ogm-sidebar"] & JSXBase.HTMLAttributes<HTMLOgmSidebarElement>;
            "ogm-viewer": LocalJSX.IntrinsicElements["ogm-viewer"] & JSXBase.HTMLAttributes<HTMLOgmViewerElement>;
        }
    }
}
