/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { PreviewError } from "./lib/errors";
import { MapGeoJSONFeature } from "maplibre-gl";
import { ResourceKind } from "./lib/resources/resource";
import { RequestTransform } from "./lib/request";
import { LayerControl } from "./lib/layers";
import { AnyPreviewer } from "./lib/previewers/factory";
export { PreviewError } from "./lib/errors";
export { MapGeoJSONFeature } from "maplibre-gl";
export { ResourceKind } from "./lib/resources/resource";
export { RequestTransform } from "./lib/request";
export { LayerControl } from "./lib/layers";
export { AnyPreviewer } from "./lib/previewers/factory";
export namespace Components {
    interface OgmAlerts {
        "error"?: PreviewError;
        /**
          * @default themePreference()
         */
        "theme": 'light' | 'dark';
    }
    interface OgmAttributes {
        /**
          * @default []
         */
        "features": MapGeoJSONFeature[];
        "kind"?: ResourceKind;
        "requestTransform"?: RequestTransform;
    }
    interface OgmImage {
        /**
          * @default 0
         */
        "padding": number;
        "previewer": ImagePreviewer;
        /**
          * @default themePreference()
         */
        "theme": 'light' | 'dark';
    }
    interface OgmLayers {
        /**
          * @default []
         */
        "layers": LayerControl[];
        "theme": 'light' | 'dark';
    }
    /**
     * Where one record is, on a map of its own: the geometry the record carries, or the box around it if
     * that is all the record has. The map GeoBlacklight draws with Leaflet beside a record's metadata.
     * One record, or one location built by hand, and nothing else. Several of them at once is a different
     * question with different answers - which of them is which, and what a reader is meant to compare -
     * and <ogm-overview> is where those are answered.
     */
    interface OgmLocator {
        "previewer"?: LocationPreviewer;
        "record"?: OgmRecord;
        /**
          * @default themePreference()
         */
        "theme": 'light' | 'dark';
    }
    interface OgmMap {
        "easeMapTo": (options: maplibregl.EaseToOptions) => Promise<maplibregl.Map>;
        /**
          * @default 0
         */
        "padding": number;
        "previewer": MapPreviewer;
        /**
          * @default themePreference()
         */
        "theme": 'light' | 'dark';
    }
    interface OgmMenubar {
        /**
          * @default false
         */
        "hideTitle": boolean;
        /**
          * @default false
         */
        "loading": boolean;
        "record": OgmRecord;
        "theme": 'light' | 'dark';
    }
    interface OgmMetadata {
        "fieldNames": string[];
        "record": OgmRecord;
        "theme": 'light' | 'dark';
    }
    /**
     * Where several records are: one numbered marker apiece, and optionally a way to search the map for
     * more of them.
     * Nothing of a record is drawn but its number. A page of boxes says less than a page of numbers a
     * reader can find again in the list beside the map, and the only two boxes worth drawing are the ones
     * that answer a question: which area is being searched, and where the one result something outside has
     * pointed at actually is. For a single record on a map of its own, see <ogm-locator>.
     */
    interface OgmOverview {
        /**
          * The area a search is currently filtered to, drawn as a box and framed by the camera. Given as the west, south, east, north degrees `boundsChange` reports, as an ENVELOPE string in the form `dcat_bbox` holds one, or as anything else MapLibre reads as bounds. A string is read from an attribute, so a page rendered by a server can say what its map is filtered to without any JavaScript at all.  It goes on holding: whenever what is drawn changes, the camera returns here rather than re-framing itself around the new set of results. Leave it unset for a map that should look at whatever it has been given.
         */
        "bounds"?: maplibregl.LngLatBoundsLike | string;
        /**
          * Whether a reader can search the map by holding shift and dragging a box over it. The area they drew is reported through `boundsChange`; nothing here answers it, because what a new area means is the embedding page's to say. The help text is a prop because GeoBlacklight runs the strings for the control this replaces through Rails I18n.
          * @default false
         */
        "geosearch": boolean;
        /**
          * Which result to bring forward, as either its place in the list counted from one or the id of the record - or of the resource a previewer draws - that it came from. An attribute hands over a string for either, since an attribute is always one.  The marker changes color and comes to the front, and the result's own extent is drawn around it. The camera doesn't move: something on the page has said which result matters, not where to look.
         */
        "highlighted"?: number | string;
        "previewers"?: LocationPreviewer[];
        "records"?: OgmRecord[];
        /**
          * @default 'Shift + drag to search an area'
         */
        "searchHelpText": string;
        /**
          * @default themePreference()
         */
        "theme": 'light' | 'dark';
    }
    interface OgmPreview {
        "previewer": AnyPreviewer;
        "sidebarPadding": number;
        /**
          * @default themePreference()
         */
        "theme": 'light' | 'dark';
    }
    interface OgmPreviews {
        "previewers"?: AnyPreviewer[];
        "record"?: OgmRecord;
        "requestTransform"?: RequestTransform;
        "sidebarPadding": number;
        /**
          * @default themePreference()
         */
        "theme": 'light' | 'dark';
    }
    interface OgmSidebar {
        /**
          * @default false
         */
        "open": boolean;
        "record": OgmRecord;
        "theme": 'light' | 'dark';
    }
    interface OgmViewer {
        /**
          * @default false
         */
        "hideTitle": boolean;
        "loadRecord": (record: OgmRecord) => Promise<void>;
        "recordUrl": string;
        "requestTransform"?: RequestTransform;
        /**
          * @default themePreference()
         */
        "theme": 'light' | 'dark';
    }
}
export interface OgmAttributesCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLOgmAttributesElement;
}
export interface OgmImageCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLOgmImageElement;
}
export interface OgmLayersCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLOgmLayersElement;
}
export interface OgmMapCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLOgmMapElement;
}
export interface OgmMenubarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLOgmMenubarElement;
}
export interface OgmOverviewCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLOgmOverviewElement;
}
export interface OgmPreviewsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLOgmPreviewsElement;
}
declare global {
    interface HTMLOgmAlertsElement extends Components.OgmAlerts, HTMLStencilElement {
    }
    var HTMLOgmAlertsElement: {
        prototype: HTMLOgmAlertsElement;
        new (): HTMLOgmAlertsElement;
    };
    interface HTMLOgmAttributesElementEventMap {
        "featureSelected": MapGeoJSONFeature;
    }
    interface HTMLOgmAttributesElement extends Components.OgmAttributes, HTMLStencilElement {
        addEventListener<K extends keyof HTMLOgmAttributesElementEventMap>(type: K, listener: (this: HTMLOgmAttributesElement, ev: OgmAttributesCustomEvent<HTMLOgmAttributesElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLOgmAttributesElementEventMap>(type: K, listener: (this: HTMLOgmAttributesElement, ev: OgmAttributesCustomEvent<HTMLOgmAttributesElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLOgmAttributesElement: {
        prototype: HTMLOgmAttributesElement;
        new (): HTMLOgmAttributesElement;
    };
    interface HTMLOgmImageElementEventMap {
        "imageLoaded": void;
        "imageLoading": void;
        "previewError": PreviewError;
    }
    interface HTMLOgmImageElement extends Components.OgmImage, HTMLStencilElement {
        addEventListener<K extends keyof HTMLOgmImageElementEventMap>(type: K, listener: (this: HTMLOgmImageElement, ev: OgmImageCustomEvent<HTMLOgmImageElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLOgmImageElementEventMap>(type: K, listener: (this: HTMLOgmImageElement, ev: OgmImageCustomEvent<HTMLOgmImageElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLOgmImageElement: {
        prototype: HTMLOgmImageElement;
        new (): HTMLOgmImageElement;
    };
    interface HTMLOgmLayersElementEventMap {
        "layerVisibilityChange": { id: string; visible: boolean };
        "layerOpacityChange": { id: string; opacity: number };
        "allLayersVisibilityChange": boolean;
    }
    interface HTMLOgmLayersElement extends Components.OgmLayers, HTMLStencilElement {
        addEventListener<K extends keyof HTMLOgmLayersElementEventMap>(type: K, listener: (this: HTMLOgmLayersElement, ev: OgmLayersCustomEvent<HTMLOgmLayersElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLOgmLayersElementEventMap>(type: K, listener: (this: HTMLOgmLayersElement, ev: OgmLayersCustomEvent<HTMLOgmLayersElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLOgmLayersElement: {
        prototype: HTMLOgmLayersElement;
        new (): HTMLOgmLayersElement;
    };
    /**
     * Where one record is, on a map of its own: the geometry the record carries, or the box around it if
     * that is all the record has. The map GeoBlacklight draws with Leaflet beside a record's metadata.
     * One record, or one location built by hand, and nothing else. Several of them at once is a different
     * question with different answers - which of them is which, and what a reader is meant to compare -
     * and <ogm-overview> is where those are answered.
     */
    interface HTMLOgmLocatorElement extends Components.OgmLocator, HTMLStencilElement {
    }
    var HTMLOgmLocatorElement: {
        prototype: HTMLOgmLocatorElement;
        new (): HTMLOgmLocatorElement;
    };
    interface HTMLOgmMapElementEventMap {
        "mapIdle": void;
        "mapLoading": void;
        "previewError": PreviewError;
    }
    interface HTMLOgmMapElement extends Components.OgmMap, HTMLStencilElement {
        addEventListener<K extends keyof HTMLOgmMapElementEventMap>(type: K, listener: (this: HTMLOgmMapElement, ev: OgmMapCustomEvent<HTMLOgmMapElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLOgmMapElementEventMap>(type: K, listener: (this: HTMLOgmMapElement, ev: OgmMapCustomEvent<HTMLOgmMapElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLOgmMapElement: {
        prototype: HTMLOgmMapElement;
        new (): HTMLOgmMapElement;
    };
    interface HTMLOgmMenubarElementEventMap {
        "sidebarToggled": any;
    }
    interface HTMLOgmMenubarElement extends Components.OgmMenubar, HTMLStencilElement {
        addEventListener<K extends keyof HTMLOgmMenubarElementEventMap>(type: K, listener: (this: HTMLOgmMenubarElement, ev: OgmMenubarCustomEvent<HTMLOgmMenubarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLOgmMenubarElementEventMap>(type: K, listener: (this: HTMLOgmMenubarElement, ev: OgmMenubarCustomEvent<HTMLOgmMenubarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLOgmMenubarElement: {
        prototype: HTMLOgmMenubarElement;
        new (): HTMLOgmMenubarElement;
    };
    interface HTMLOgmMetadataElement extends Components.OgmMetadata, HTMLStencilElement {
    }
    var HTMLOgmMetadataElement: {
        prototype: HTMLOgmMetadataElement;
        new (): HTMLOgmMetadataElement;
    };
    interface HTMLOgmOverviewElementEventMap {
        "boundsChange": [number, number, number, number];
    }
    /**
     * Where several records are: one numbered marker apiece, and optionally a way to search the map for
     * more of them.
     * Nothing of a record is drawn but its number. A page of boxes says less than a page of numbers a
     * reader can find again in the list beside the map, and the only two boxes worth drawing are the ones
     * that answer a question: which area is being searched, and where the one result something outside has
     * pointed at actually is. For a single record on a map of its own, see <ogm-locator>.
     */
    interface HTMLOgmOverviewElement extends Components.OgmOverview, HTMLStencilElement {
        addEventListener<K extends keyof HTMLOgmOverviewElementEventMap>(type: K, listener: (this: HTMLOgmOverviewElement, ev: OgmOverviewCustomEvent<HTMLOgmOverviewElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLOgmOverviewElementEventMap>(type: K, listener: (this: HTMLOgmOverviewElement, ev: OgmOverviewCustomEvent<HTMLOgmOverviewElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLOgmOverviewElement: {
        prototype: HTMLOgmOverviewElement;
        new (): HTMLOgmOverviewElement;
    };
    interface HTMLOgmPreviewElement extends Components.OgmPreview, HTMLStencilElement {
    }
    var HTMLOgmPreviewElement: {
        prototype: HTMLOgmPreviewElement;
        new (): HTMLOgmPreviewElement;
    };
    interface HTMLOgmPreviewsElementEventMap {
        "previewsLoading": void;
        "previewsLoaded": void;
    }
    interface HTMLOgmPreviewsElement extends Components.OgmPreviews, HTMLStencilElement {
        addEventListener<K extends keyof HTMLOgmPreviewsElementEventMap>(type: K, listener: (this: HTMLOgmPreviewsElement, ev: OgmPreviewsCustomEvent<HTMLOgmPreviewsElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLOgmPreviewsElementEventMap>(type: K, listener: (this: HTMLOgmPreviewsElement, ev: OgmPreviewsCustomEvent<HTMLOgmPreviewsElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLOgmPreviewsElement: {
        prototype: HTMLOgmPreviewsElement;
        new (): HTMLOgmPreviewsElement;
    };
    interface HTMLOgmSidebarElement extends Components.OgmSidebar, HTMLStencilElement {
    }
    var HTMLOgmSidebarElement: {
        prototype: HTMLOgmSidebarElement;
        new (): HTMLOgmSidebarElement;
    };
    interface HTMLOgmViewerElement extends Components.OgmViewer, HTMLStencilElement {
    }
    var HTMLOgmViewerElement: {
        prototype: HTMLOgmViewerElement;
        new (): HTMLOgmViewerElement;
    };
    interface HTMLElementTagNameMap {
        "ogm-alerts": HTMLOgmAlertsElement;
        "ogm-attributes": HTMLOgmAttributesElement;
        "ogm-image": HTMLOgmImageElement;
        "ogm-layers": HTMLOgmLayersElement;
        "ogm-locator": HTMLOgmLocatorElement;
        "ogm-map": HTMLOgmMapElement;
        "ogm-menubar": HTMLOgmMenubarElement;
        "ogm-metadata": HTMLOgmMetadataElement;
        "ogm-overview": HTMLOgmOverviewElement;
        "ogm-preview": HTMLOgmPreviewElement;
        "ogm-previews": HTMLOgmPreviewsElement;
        "ogm-sidebar": HTMLOgmSidebarElement;
        "ogm-viewer": HTMLOgmViewerElement;
    }
}
declare namespace LocalJSX {
    interface OgmAlerts {
        "error"?: PreviewError;
        /**
          * @default themePreference()
         */
        "theme"?: 'light' | 'dark';
    }
    interface OgmAttributes {
        /**
          * @default []
         */
        "features"?: MapGeoJSONFeature[];
        "kind"?: ResourceKind;
        "onFeatureSelected"?: (event: OgmAttributesCustomEvent<MapGeoJSONFeature>) => void;
        "requestTransform"?: RequestTransform;
    }
    interface OgmImage {
        "onImageLoaded"?: (event: OgmImageCustomEvent<void>) => void;
        "onImageLoading"?: (event: OgmImageCustomEvent<void>) => void;
        "onPreviewError"?: (event: OgmImageCustomEvent<PreviewError>) => void;
        /**
          * @default 0
         */
        "padding"?: number;
        "previewer"?: ImagePreviewer;
        /**
          * @default themePreference()
         */
        "theme"?: 'light' | 'dark';
    }
    interface OgmLayers {
        /**
          * @default []
         */
        "layers"?: LayerControl[];
        "onAllLayersVisibilityChange"?: (event: OgmLayersCustomEvent<boolean>) => void;
        "onLayerOpacityChange"?: (event: OgmLayersCustomEvent<{ id: string; opacity: number }>) => void;
        "onLayerVisibilityChange"?: (event: OgmLayersCustomEvent<{ id: string; visible: boolean }>) => void;
        "theme"?: 'light' | 'dark';
    }
    /**
     * Where one record is, on a map of its own: the geometry the record carries, or the box around it if
     * that is all the record has. The map GeoBlacklight draws with Leaflet beside a record's metadata.
     * One record, or one location built by hand, and nothing else. Several of them at once is a different
     * question with different answers - which of them is which, and what a reader is meant to compare -
     * and <ogm-overview> is where those are answered.
     */
    interface OgmLocator {
        "previewer"?: LocationPreviewer;
        "record"?: OgmRecord;
        /**
          * @default themePreference()
         */
        "theme"?: 'light' | 'dark';
    }
    interface OgmMap {
        "onMapIdle"?: (event: OgmMapCustomEvent<void>) => void;
        "onMapLoading"?: (event: OgmMapCustomEvent<void>) => void;
        "onPreviewError"?: (event: OgmMapCustomEvent<PreviewError>) => void;
        /**
          * @default 0
         */
        "padding"?: number;
        "previewer"?: MapPreviewer;
        /**
          * @default themePreference()
         */
        "theme"?: 'light' | 'dark';
    }
    interface OgmMenubar {
        /**
          * @default false
         */
        "hideTitle"?: boolean;
        /**
          * @default false
         */
        "loading"?: boolean;
        "onSidebarToggled"?: (event: OgmMenubarCustomEvent<any>) => void;
        "record"?: OgmRecord;
        "theme"?: 'light' | 'dark';
    }
    interface OgmMetadata {
        "fieldNames"?: string[];
        "record"?: OgmRecord;
        "theme"?: 'light' | 'dark';
    }
    /**
     * Where several records are: one numbered marker apiece, and optionally a way to search the map for
     * more of them.
     * Nothing of a record is drawn but its number. A page of boxes says less than a page of numbers a
     * reader can find again in the list beside the map, and the only two boxes worth drawing are the ones
     * that answer a question: which area is being searched, and where the one result something outside has
     * pointed at actually is. For a single record on a map of its own, see <ogm-locator>.
     */
    interface OgmOverview {
        /**
          * The area a search is currently filtered to, drawn as a box and framed by the camera. Given as the west, south, east, north degrees `boundsChange` reports, as an ENVELOPE string in the form `dcat_bbox` holds one, or as anything else MapLibre reads as bounds. A string is read from an attribute, so a page rendered by a server can say what its map is filtered to without any JavaScript at all.  It goes on holding: whenever what is drawn changes, the camera returns here rather than re-framing itself around the new set of results. Leave it unset for a map that should look at whatever it has been given.
         */
        "bounds"?: maplibregl.LngLatBoundsLike | string;
        /**
          * Whether a reader can search the map by holding shift and dragging a box over it. The area they drew is reported through `boundsChange`; nothing here answers it, because what a new area means is the embedding page's to say. The help text is a prop because GeoBlacklight runs the strings for the control this replaces through Rails I18n.
          * @default false
         */
        "geosearch"?: boolean;
        /**
          * Which result to bring forward, as either its place in the list counted from one or the id of the record - or of the resource a previewer draws - that it came from. An attribute hands over a string for either, since an attribute is always one.  The marker changes color and comes to the front, and the result's own extent is drawn around it. The camera doesn't move: something on the page has said which result matters, not where to look.
         */
        "highlighted"?: number | string;
        "onBoundsChange"?: (event: OgmOverviewCustomEvent<[number, number, number, number]>) => void;
        "previewers"?: LocationPreviewer[];
        "records"?: OgmRecord[];
        /**
          * @default 'Shift + drag to search an area'
         */
        "searchHelpText"?: string;
        /**
          * @default themePreference()
         */
        "theme"?: 'light' | 'dark';
    }
    interface OgmPreview {
        "previewer"?: AnyPreviewer;
        "sidebarPadding"?: number;
        /**
          * @default themePreference()
         */
        "theme"?: 'light' | 'dark';
    }
    interface OgmPreviews {
        "onPreviewsLoaded"?: (event: OgmPreviewsCustomEvent<void>) => void;
        "onPreviewsLoading"?: (event: OgmPreviewsCustomEvent<void>) => void;
        "previewers"?: AnyPreviewer[];
        "record"?: OgmRecord;
        "requestTransform"?: RequestTransform;
        "sidebarPadding"?: number;
        /**
          * @default themePreference()
         */
        "theme"?: 'light' | 'dark';
    }
    interface OgmSidebar {
        /**
          * @default false
         */
        "open"?: boolean;
        "record"?: OgmRecord;
        "theme"?: 'light' | 'dark';
    }
    interface OgmViewer {
        /**
          * @default false
         */
        "hideTitle"?: boolean;
        "recordUrl"?: string;
        "requestTransform"?: RequestTransform;
        /**
          * @default themePreference()
         */
        "theme"?: 'light' | 'dark';
    }

    interface OgmAlertsAttributes {
        "theme": 'light' | 'dark';
    }
    interface OgmAttributesAttributes {
        "kind": ResourceKind;
    }
    interface OgmImageAttributes {
        "theme": 'light' | 'dark';
        "padding": number;
    }
    interface OgmLayersAttributes {
        "theme": 'light' | 'dark';
    }
    interface OgmLocatorAttributes {
        "theme": 'light' | 'dark';
    }
    interface OgmMapAttributes {
        "theme": 'light' | 'dark';
        "padding": number;
    }
    interface OgmMenubarAttributes {
        "theme": 'light' | 'dark';
        "loading": boolean;
        "hideTitle": boolean;
    }
    interface OgmMetadataAttributes {
        "theme": 'light' | 'dark';
    }
    interface OgmOverviewAttributes {
        "theme": 'light' | 'dark';
        "highlighted": string;
        "geosearch": boolean;
        "searchHelpText": string;
        "bounds": maplibregl.LngLatBoundsLike | string;
    }
    interface OgmPreviewAttributes {
        "theme": 'light' | 'dark';
        "sidebarPadding": number;
    }
    interface OgmPreviewsAttributes {
        "theme": 'light' | 'dark';
        "sidebarPadding": number;
    }
    interface OgmSidebarAttributes {
        "theme": 'light' | 'dark';
        "open": boolean;
    }
    interface OgmViewerAttributes {
        "recordUrl": string;
        "theme": 'light' | 'dark';
        "hideTitle": boolean;
    }

    interface IntrinsicElements {
        "ogm-alerts": Omit<OgmAlerts, keyof OgmAlertsAttributes> & { [K in keyof OgmAlerts & keyof OgmAlertsAttributes]?: OgmAlerts[K] } & { [K in keyof OgmAlerts & keyof OgmAlertsAttributes as `attr:${K}`]?: OgmAlertsAttributes[K] } & { [K in keyof OgmAlerts & keyof OgmAlertsAttributes as `prop:${K}`]?: OgmAlerts[K] };
        "ogm-attributes": Omit<OgmAttributes, keyof OgmAttributesAttributes> & { [K in keyof OgmAttributes & keyof OgmAttributesAttributes]?: OgmAttributes[K] } & { [K in keyof OgmAttributes & keyof OgmAttributesAttributes as `attr:${K}`]?: OgmAttributesAttributes[K] } & { [K in keyof OgmAttributes & keyof OgmAttributesAttributes as `prop:${K}`]?: OgmAttributes[K] };
        "ogm-image": Omit<OgmImage, keyof OgmImageAttributes> & { [K in keyof OgmImage & keyof OgmImageAttributes]?: OgmImage[K] } & { [K in keyof OgmImage & keyof OgmImageAttributes as `attr:${K}`]?: OgmImageAttributes[K] } & { [K in keyof OgmImage & keyof OgmImageAttributes as `prop:${K}`]?: OgmImage[K] };
        "ogm-layers": Omit<OgmLayers, keyof OgmLayersAttributes> & { [K in keyof OgmLayers & keyof OgmLayersAttributes]?: OgmLayers[K] } & { [K in keyof OgmLayers & keyof OgmLayersAttributes as `attr:${K}`]?: OgmLayersAttributes[K] } & { [K in keyof OgmLayers & keyof OgmLayersAttributes as `prop:${K}`]?: OgmLayers[K] };
        "ogm-locator": Omit<OgmLocator, keyof OgmLocatorAttributes> & { [K in keyof OgmLocator & keyof OgmLocatorAttributes]?: OgmLocator[K] } & { [K in keyof OgmLocator & keyof OgmLocatorAttributes as `attr:${K}`]?: OgmLocatorAttributes[K] } & { [K in keyof OgmLocator & keyof OgmLocatorAttributes as `prop:${K}`]?: OgmLocator[K] };
        "ogm-map": Omit<OgmMap, keyof OgmMapAttributes> & { [K in keyof OgmMap & keyof OgmMapAttributes]?: OgmMap[K] } & { [K in keyof OgmMap & keyof OgmMapAttributes as `attr:${K}`]?: OgmMapAttributes[K] } & { [K in keyof OgmMap & keyof OgmMapAttributes as `prop:${K}`]?: OgmMap[K] };
        "ogm-menubar": Omit<OgmMenubar, keyof OgmMenubarAttributes> & { [K in keyof OgmMenubar & keyof OgmMenubarAttributes]?: OgmMenubar[K] } & { [K in keyof OgmMenubar & keyof OgmMenubarAttributes as `attr:${K}`]?: OgmMenubarAttributes[K] } & { [K in keyof OgmMenubar & keyof OgmMenubarAttributes as `prop:${K}`]?: OgmMenubar[K] };
        "ogm-metadata": Omit<OgmMetadata, keyof OgmMetadataAttributes> & { [K in keyof OgmMetadata & keyof OgmMetadataAttributes]?: OgmMetadata[K] } & { [K in keyof OgmMetadata & keyof OgmMetadataAttributes as `attr:${K}`]?: OgmMetadataAttributes[K] } & { [K in keyof OgmMetadata & keyof OgmMetadataAttributes as `prop:${K}`]?: OgmMetadata[K] };
        "ogm-overview": Omit<OgmOverview, keyof OgmOverviewAttributes> & { [K in keyof OgmOverview & keyof OgmOverviewAttributes]?: OgmOverview[K] } & { [K in keyof OgmOverview & keyof OgmOverviewAttributes as `attr:${K}`]?: OgmOverviewAttributes[K] } & { [K in keyof OgmOverview & keyof OgmOverviewAttributes as `prop:${K}`]?: OgmOverview[K] };
        "ogm-preview": Omit<OgmPreview, keyof OgmPreviewAttributes> & { [K in keyof OgmPreview & keyof OgmPreviewAttributes]?: OgmPreview[K] } & { [K in keyof OgmPreview & keyof OgmPreviewAttributes as `attr:${K}`]?: OgmPreviewAttributes[K] } & { [K in keyof OgmPreview & keyof OgmPreviewAttributes as `prop:${K}`]?: OgmPreview[K] };
        "ogm-previews": Omit<OgmPreviews, keyof OgmPreviewsAttributes> & { [K in keyof OgmPreviews & keyof OgmPreviewsAttributes]?: OgmPreviews[K] } & { [K in keyof OgmPreviews & keyof OgmPreviewsAttributes as `attr:${K}`]?: OgmPreviewsAttributes[K] } & { [K in keyof OgmPreviews & keyof OgmPreviewsAttributes as `prop:${K}`]?: OgmPreviews[K] };
        "ogm-sidebar": Omit<OgmSidebar, keyof OgmSidebarAttributes> & { [K in keyof OgmSidebar & keyof OgmSidebarAttributes]?: OgmSidebar[K] } & { [K in keyof OgmSidebar & keyof OgmSidebarAttributes as `attr:${K}`]?: OgmSidebarAttributes[K] } & { [K in keyof OgmSidebar & keyof OgmSidebarAttributes as `prop:${K}`]?: OgmSidebar[K] };
        "ogm-viewer": Omit<OgmViewer, keyof OgmViewerAttributes> & { [K in keyof OgmViewer & keyof OgmViewerAttributes]?: OgmViewer[K] } & { [K in keyof OgmViewer & keyof OgmViewerAttributes as `attr:${K}`]?: OgmViewerAttributes[K] } & { [K in keyof OgmViewer & keyof OgmViewerAttributes as `prop:${K}`]?: OgmViewer[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ogm-alerts": LocalJSX.IntrinsicElements["ogm-alerts"] & JSXBase.HTMLAttributes<HTMLOgmAlertsElement>;
            "ogm-attributes": LocalJSX.IntrinsicElements["ogm-attributes"] & JSXBase.HTMLAttributes<HTMLOgmAttributesElement>;
            "ogm-image": LocalJSX.IntrinsicElements["ogm-image"] & JSXBase.HTMLAttributes<HTMLOgmImageElement>;
            "ogm-layers": LocalJSX.IntrinsicElements["ogm-layers"] & JSXBase.HTMLAttributes<HTMLOgmLayersElement>;
            /**
             * Where one record is, on a map of its own: the geometry the record carries, or the box around it if
             * that is all the record has. The map GeoBlacklight draws with Leaflet beside a record's metadata.
             * One record, or one location built by hand, and nothing else. Several of them at once is a different
             * question with different answers - which of them is which, and what a reader is meant to compare -
             * and <ogm-overview> is where those are answered.
             */
            "ogm-locator": LocalJSX.IntrinsicElements["ogm-locator"] & JSXBase.HTMLAttributes<HTMLOgmLocatorElement>;
            "ogm-map": LocalJSX.IntrinsicElements["ogm-map"] & JSXBase.HTMLAttributes<HTMLOgmMapElement>;
            "ogm-menubar": LocalJSX.IntrinsicElements["ogm-menubar"] & JSXBase.HTMLAttributes<HTMLOgmMenubarElement>;
            "ogm-metadata": LocalJSX.IntrinsicElements["ogm-metadata"] & JSXBase.HTMLAttributes<HTMLOgmMetadataElement>;
            /**
             * Where several records are: one numbered marker apiece, and optionally a way to search the map for
             * more of them.
             * Nothing of a record is drawn but its number. A page of boxes says less than a page of numbers a
             * reader can find again in the list beside the map, and the only two boxes worth drawing are the ones
             * that answer a question: which area is being searched, and where the one result something outside has
             * pointed at actually is. For a single record on a map of its own, see <ogm-locator>.
             */
            "ogm-overview": LocalJSX.IntrinsicElements["ogm-overview"] & JSXBase.HTMLAttributes<HTMLOgmOverviewElement>;
            "ogm-preview": LocalJSX.IntrinsicElements["ogm-preview"] & JSXBase.HTMLAttributes<HTMLOgmPreviewElement>;
            "ogm-previews": LocalJSX.IntrinsicElements["ogm-previews"] & JSXBase.HTMLAttributes<HTMLOgmPreviewsElement>;
            "ogm-sidebar": LocalJSX.IntrinsicElements["ogm-sidebar"] & JSXBase.HTMLAttributes<HTMLOgmSidebarElement>;
            "ogm-viewer": LocalJSX.IntrinsicElements["ogm-viewer"] & JSXBase.HTMLAttributes<HTMLOgmViewerElement>;
        }
    }
}
